export const GET_AVAILABLE_CLAIMS = 'GET_AVAILABLE_CLAIMS';
export const SET_LOCK_UNLOCK_CLAIMS = 'SET_LOCK_UNLOCK_CLAIMS';
export const RESET_LOCK_UNLOCK_CLAIMS = 'RESET_LOCK_UNLOCK_CLAIMS';
export const GET_CLAIMS_HISTORY = 'GET_CLAIMS_HISTORY';
