export const TOGGLE_THEME = 'TOGGLE_THEME';
export const LOADING = 'LOADING';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
export const INITIALLY_RENDERED = 'INITIALLY_RENDERED';
